name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        package:
          - portainer
          - hedgedoc
          - dozzle
          - memos
    steps:
      - uses: actions/checkout@v5
      - env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          cd ${{ matrix.package }}
          sops -d ../.enc.env > .env
          docker compose pull
          docker compose up --detach --remove-orphans
          docker image prune --force
          rm .env
